### ISSUE TITLE
Protections don't work when a nonexistent group/permission is added

### ISSUE THREAD

**Issue by jack-pie** [pop4959/Bolt#6]
If you specify a nonexistent group (or permission) in `/bolt edit add admin`, the given protection stops working.

This also applies to `/bolt trust`, but has a global effect.

Tried this only on a Purpur (`1.19.3`, build: `1924`) server with the newest version of Bolt.

```
[23:57:39 ERROR]: Could not pass event PlayerInteractEvent to Bolt v1.0.319
java.lang.NullPointerException: Cannot invoke "org.popcraft.bolt.access.AccessList.getAccess()" because the return value of "java.util.concurrent.CompletableFuture.join()" is null
        at org.popcraft.bolt.BoltPlugin.canAccess(BoltPlugin.java:491) ~[Bolt-1.0.319.jar:?]
        at org.popcraft.bolt.BoltPlugin.canAccess(BoltPlugin.java:475) ~[Bolt-1.0.319.jar:?]
        at org.popcraft.bolt.BoltPlugin.canAccess(BoltPlugin.java:471) ~[Bolt-1.0.319.jar:?]
        at org.popcraft.bolt.listeners.BlockListener.onPlayerInteract(BlockListener.java:97) ~[Bolt-1.0.319.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor52.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1924]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.3.jar:git-Purpur-1924]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.3.jar:git-Purpur-1924]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:546) ~[purpur-1.19.3.jar:git-Purpur-1924]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:530) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2040) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1924]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.3.jar:git-Purpur-1924]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1924]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1924]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.3.jar:git-Purpur-1924]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.3.jar:git-Purpur-1924]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.3.jar:git-Purpur-1924]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1924]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        ```

**Comment by pop4959** [comment]
Thanks for the report, it looks like this actually happens when the player has no access list.

I don't think non-existent groups or permissions should be an issue, they just won't resolve to anything. Though do let me know if you find anything acting weird there.

Latest version fixes this error, and protections should work normally.

**Comment by pop4959** [comment]
Sorry, there was actually also an issue with groups as you mentioned. It just wasn't in the error you reported.

Latest build fixes both of these things, sorry about that! Should be much more stable onward.
